# Generated by Django 3.2.9 on 2021-11-10 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('numero_cuenta', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cbu', models.CharField(max_length=22, unique=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('banco_emisor', models.CharField(choices=[('1', 'Banco central'), ('2', 'Banco Nacion')], max_length=1)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
    ]
